### ISSUE TITLE
验证的时候失败了

### ISSUE THREAD

**Issue by mybee** [durarara5/slide_captcha#4]
一次为什么会下载很多滑动图片呢, 这个不是很清楚. 
![image](https://user-images.githubusercontent.com/8556916/63563479-d53e3900-c593-11e9-800b-edf3de5db165.png)

方便加下微信么? 18844736952

**Comment by mybee** [comment]
**打印的日志:**

滑动距离：95
使用轨迹94
jQuery1102012450457664137127_1566490138246({"message":"校验失败","data":{"ischange":false,"status":1},"code":0})
滑动距离：132
使用轨迹130
调整轨迹130=>132
jQuery1102012450457664137127_1566490138246({"message":"校验成功","data":{"sourceimg":"/captcha/source_img/ba6903fce64fe3f389def7c97d30e6553dd12aa650392be634cd7a8fbc6f2a2aa8ef4f0d1b36f4ce4408436ca004df5d19480a900fee6c4d34186d581d682dbb","status":0,"successToken":"02f3fb75eb844df8b319a4685f791263"},"code":0})
滑动距离：234
使用轨迹232
调整轨迹232=>234
jQuery1102012450457664137127_1566490138246({"message":"校验失败","data":{"ischange":false,"status":1},"code":0})
滑动距离：2
超出范围1
滑动距离：79
使用轨迹78
jQuery1102012450457664137127_1566490138246({"message":"校验失败","data":{"ischange":false,"status":1},"code":0})
滑动距离：0
超出范围1
滑动距离：174
使用轨迹174
jQuery1102012450457664137127_1566490138246({"message":"校验成功","data":{"sourceimg":"/captcha/source_img/0f80d69e2838923e4cf5785c2953d50636e77a55400eb177a97bcc25d4479fc048d6bab1f61ee1b04c497d7ac7de85fe9a8caa2e3dd288a0a8ae045858a6da69","status":0,"successToken":"4753f91d1010417fb3156fadeeb5a01b"},"code":0})
滑动距离：124
使用轨迹122
调整轨迹122=>124
jQuery1102012450457664137127_1566490138246({"message":"校验失败","data":{"ischange":false,"status":1},"code":0})
滑动距离：162
使用轨迹162
jQuery1102012450457664137127_1566490138246({"message":"校验成功","data":{"sourceimg":"/captcha/source_img/b51a093eb08f92627c9f4c3a8c18bef2a960ca468567ab6ebe1b946c28cdbb1d0b39d30e1a826efb49db803ce2fbe88b7c62eb2cd8a58cd946c1c0ce10133ace","status":0,"successToken":"3a33773096ba4ea387e365464bc124fe"},"code":0})

**Comment by durarara5** [comment]
一次验证需要一张原图一张拼图块 我主函数里循环执行了10次，你可以自行修改
另外轨迹是通过抓包拿到的，再随机添加几步，并不能保证每次都能验证通过，tools文件夹里有脚本可以自行抓包获取更多轨迹

**Comment by mybee** [comment]
嗯嗯,  为什么jQuery1102012450457664137127_1566490138246({"message":"校验成功","data":{"sourceimg":"/captcha/source_img/b50bbef547a32cc9a2529ab53db8ecfbac920f4db6002619890e774bc54b516a8969dde2efeb040785fc9f9fa6df7c25072a7ef8284bfa2d67b2cc5f22248f78","status":0,"successToken":"62642171ed1d4fa7974c50b25dbece6f"},"code":0})

校验成功的时候也会弹出data sourceimg 字段 继续校验....

是识别出不是人操作的吗?

 可以加个微信吗, 需要你帮下忙, 有偿的.

**Comment by mybee** [comment]
问下, 验证的时候  是否需要跟出现验证的地方 一个ip下才可以吗?

**Comment by durarara5** [comment]
现在手动验证有时也会出现二次验证，不一定是判断为机器 
具体的规则不太清楚，你可以在页面上手动验证观察一下

**Comment by mybee** [comment]
jQuery110206674310031126027_1565319013272({"message":"校验成功","data":{"sourceimg":"/captcha/source_img/37176ab988356d4578090ec217845245b949aab5321143b3a901225079afa38a22b66e9a968c722794972943afea0c2b76e3172859ed867a0ca3e764261bb4f7","status":0,"successToken":"e5e6fe3e5cdf4f83ad896397823d012f"},"code":0})  这个里面的sourceimg 可以破解吗?

**Comment by durarara5** [comment]
其他形式的验证码暂时没有研究
